// Actions
//Get Category
export const GET_ROLE_PERMISSIONS_REQUEST = 'GET_ROLE_PERMISSIONS_REQUEST';
export const GET_ROLE_PERMISSIONS_SUCCESS = 'GET_ROLE_PERMISSIONS_SUCCESS';
export const GET_ROLE_PERMISSIONS_FAIL = 'GET_ROLE_PERMISSIONS_FAIL';

//Add Category
export const ADD_ROLE_PERMISSIONS_REQUEST = 'ADD_ROLE_PERMISSIONS_REQUEST';
export const ADD_ROLE_PERMISSIONS_SUCCESS = 'ADD_ROLE_PERMISSIONS_SUCCESS';
export const ADD_ROLE_PERMISSIONS_FAIL = 'ADD_ROLE_PERMISSIONS_FAIL';
export const ADD_ROLE_PERMISSIONS_RESET = 'ADD_ROLE_PERMISSIONS_RESET'



/**
 * Edit Category
 */
export const UPDATE_ROLE_PERMISSIONS = "UPDATE_ROLE_PERMISSIONS"
export const UPDATE_ROLE_PERMISSIONS_SUCCESS = "UPDATE_ROLE_PERMISSIONS_SUCCESS"
export const UPDATE_ROLE_PERMISSIONS_FAIL = "UPDATE_ROLE_PERMISSIONS_FAIL"
export const  UPDATE_ROLE_PERMISSIONS_RESET = ' UPDATE_ROLE_PERMISSIONS_RESET'


/**
 * Delete Category
 */
export const DELETE_ROLE_PERMISSIONS = "DELETE_ROLE_PERMISSIONS"
export const DELETE_ROLE_PERMISSIONS_SUCCESS = "DELETE_ROLE_PERMISSIONS_SUCCESS"
export const DELETE_ROLE_PERMISSIONS_FAIL = "DELETE_ROLE_PERMISSIONS_FAIL"

