// Actions
//Get Category
export const GET_PERMISSIONS_REQUEST = 'GET_PERMISSIONS_REQUEST';
export const GET_PERMISSIONS_SUCCESS = 'GET_PERMISSIONS_SUCCESS';
export const GET_PERMISSIONS_FAIL = 'GET_PERMISSIONS_FAIL';

//Add Category
export const ADD_PERMISSIONS_REQUEST = 'ADD_PERMISSIONS_REQUEST';
export const ADD_PERMISSIONS_SUCCESS = 'ADD_PERMISSIONS_SUCCESS';
export const ADD_PERMISSIONS_FAIL = 'ADD_PERMISSIONS_FAIL';
export const ADD_PERMISSIONS_RESET = 'ADD_PERMISSIONS_RESET'



/**
 * Edit Category
 */
export const UPDATE_PERMISSIONS = "UPDATE_PERMISSIONS"
export const UPDATE_PERMISSIONS_SUCCESS = "UPDATE_PERMISSIONS_SUCCESS"
export const UPDATE_PERMISSIONS_FAIL = "UPDATE_PERMISSIONS_FAIL"
export const  UPDATE_PERMISSIONS_RESET = ' UPDATE_PERMISSIONS_RESET'


/**
 * Delete Category
 */
export const DELETE_PERMISSIONS = "DELETE_PERMISSIONS"
export const DELETE_PERMISSIONS_SUCCESS = "DELETE_PERMISSIONS_SUCCESS"
export const DELETE_PERMISSIONS_FAIL = "DELETE_PERMISSIONS_FAIL"

