// Actions
//Get Routes
export const GET_ROUTES_REQUEST = 'GET_ROUTES_REQUEST';
export const GET_ROUTES_SUCCESS = 'GET_ROUTES_SUCCESS';
export const GET_ROUTES_FAIL = 'GET_ROUTES_FAIL';

//Add Routes
export const ADD_ROUTES_REQUEST = 'ADD_ROUTES_REQUEST';
export const ADD_ROUTES_SUCCESS = 'ADD_ROUTES_SUCCESS';
export const ADD_ROUTES_FAIL = 'ADD_ROUTES_FAIL';
export const ADD_ROUTES_RESET = 'ADD_ROUTES_RESET'



/**
 * Edit Routes
 */
export const UPDATE_ROUTES = "UPDATE_ROUTES"
export const UPDATE_ROUTES_SUCCESS = "UPDATE_ROUTES_SUCCESS"
export const UPDATE_ROUTES_FAIL = "UPDATE_ROUTES_FAIL"
export const  UPDATE_ROUTES_RESET = ' UPDATE_ROUTES_RESET'


/**
 * Delete Routes
 */
export const DELETE_ROUTES = "DELETE_ROUTES"
export const DELETE_ROUTES_SUCCESS = "DELETE_ROUTES_SUCCESS"
export const DELETE_ROUTES_FAIL = "DELETE_ROUTES_FAIL"

